<a href="https://colab.research.google.com/github/DemydovaAnna/python_for_da_tasks/blob/main/Copy_of_hw_10_4_apply%2C_groupby%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('drive/MyDrive/Dataloveacademy/Модуль 10. Бібліотека Pandas: ключові концепції та методи роботи з даними/supermarket_sales.csv')
print(type(df))

<class 'pandas.core.frame.DataFrame'>

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [4]:
df.groupby('Branch')['gross income'].sum()

Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [5]:
df.groupby(['City', 'Branch'])['gross income'].sum()

City       Branch
Mandalay   B         5057.0320
Naypyitaw  C         5265.1765
Yangon     A         5057.1605
Name: gross income, dtype: float64

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [6]:
invoices_by_category = df.pivot_table(
    index='Branch',
    columns='Product line',
    values='Invoice ID',
    aggfunc='count'
)

invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [7]:
invoices_by_category['Electronic accessories'].idxmax()

'A'

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

# Гіпотези:
1. Зв'язок статі покупця і категорії товарів.
2. Спосіб оплати серед постійних та звичайних покупців.
3. Прибутковість категорій товарів у розрізі філій (Branch vs Product line)

In [8]:
#Гіпотеза №1
df.groupby(['Gender', 'Product line'])['Total'].mean().unstack()

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,322.643125,317.056250,368.565750,290.015414,380.213639,324.712739
Male,316.691965,291.079207,273.499125,348.099460,294.136241,340.360327

In [9]:
#Гіпотеза №2
df.pivot_table(index='Customer type', columns='Payment', values='Invoice ID', aggfunc='count')

Payment        Cash  Credit card  Ewallet
Customer type
Member          168          172      161
Normal          176          139      184

In [17]:
#Гіпотеза №3
df.pivot_table(index='Branch', columns='Product line', values='gross income', aggfunc='sum')

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,872.2435,777.7385,817.2905,599.893,1067.4855,922.5095
B,811.9735,781.5865,724.5185,951.460,835.6745,951.8190
C,903.2845,1026.6700,1131.7550,791.206,661.6930,750.5680

# Висновки та рекомендації:
1. Зв'язок статі покупця та категорій товарів
 **Висновок**: Жінки витрачають суттєво більше за один чек у категоріях Food and beverages та Home and lifestyle. Натомість чоловіки залишають більше грошей у категорії Health and beauty.
 **Рекомендація**: Формувати персональні акції та бандли (комплекти): для жінок розширювати асортимент сімейних наборів у продуктах та товарів для дому, а в категорії догляду/краси (⁠Health and beauty⁠) робити фокус на чоловічих лінійках та подарункових наборах. Якщо чоловіки купують догляд (⁠Health and beauty⁠) як подарунки, напередодні свят ці товари треба виставляти на найвидиміших місцях і одразу пропонувати подарункове пакування. Це підніме чек без додаткових витрат.
2. Спосіб оплати серед постійних та звичайних клієнтів
 **Висновок**: Члени клубу (⁠Member⁠) найчастіше розраховуються Credit card  та Cash, тоді як звичайні покупці (⁠Normal⁠) найбільше віддають перевагу Ewallet.
 **Рекомендація**: Запустити маркетингову кампанію з електронними гаманцями (Ewallet): пропонувати миттєву знижку або бонуси при оформленні картки ⁠Member⁠ за умови оплати через Ewallet. Це дозволить конвертувати велику базу звичайних покупців у постійних клієнтів.
3. Прибутковість категорій товарів у розрізі філій (Branch vs Product line)
**Висновок**: Кожна філія має свою чітку товарну специфіку та джерела валового прибутку (⁠gross income⁠). Філіал A генерує найбільше прибутку на товарах для дому (⁠Home and lifestyle⁠), філіал B — на доглядовій косметиці (⁠Health and beauty⁠) та спорті, а філіал C — на їжі (⁠Food and beverages⁠) та моді (⁠Fashion accessories⁠).
**Рекомендація**: Відмовитися від стандартної (однакової) матриці закупівель для всіх магазинів.
- Оптимізація торгових площ: У філіалі C розширити полиці під продукти харчування та одяг за рахунок скорочення відділу товарів для дому.
- Локальні промо-акції: Направляти маркетинговий бюджет кожного філіалу на просування його завідомо найсильніших категорій, замість спроб рекламувати неходові товари (як ⁠Health and beauty⁠ у філіалі A).